volumes:
  postgres-data:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
    environment:
      DATABASE_PASSWORD: 'postgres'
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 10 && rails db:create && rails db:migrate && rails s -b 0.0.0.0"
    depends_on:
      - 'db'

  db:
    image: 'postgres:12.19-alpine3.20'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    # ports:
    #   - "5432:5432"
