volumes:
  postgres-data:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
    environment:
      DATABASE_PASSWORD: 'postgres'
    tty: true
    stdin_open: true
    entrypoint: /bin/bash docker-entrypoint.sh
    command: /bin/bash -c "rails db:migrate && rails s -b 0.0.0.0"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'postgres:12.19-alpine3.20'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
